baseURL = 'https://robinpeutlschmid.cz/'   # or https://<user>.github.io/
defaultContentLanguage = "en"                      # or 'en-us'; set per your primary language
title = 'Robin Peutlschmid'
theme = 'blowfish'
enableRobotsTXT = true
summaryLength = 0

[pagination]
	pagersize = 10

[outputs]
	home = ["HTML", "RSS", "JSON"]

[taxonomies]
	tag = "tags"
	category = "categories"
	series = "series"
	world = "worlds"

[caches]
  [caches.images]
    dir = ':cacheDir/images'   # lets CI cache processed images between builds
